### PR TITLE
rewrite

### PR DESCRIPTION
**Pull request by extreme4all**

### CODE REVIEW

**Review by Ferrariic — APPROVED** [review]
No obvious errors.

**Comment by extreme4all** [comment]
TODO: check for allowed channels

**Comment by extreme4all** [comment]
@Ferrariic better review the darn PR now

**Comment by Ferrariic** [comment]
> @Ferrariic better review the darn PR now

IT'S TIME

**Comment by Ferrariic** [comment]
Approved

**Pull request merged**
